# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
   app_admin.twig.extension:
       class: AppBundle\Twig\TablonExtension
       arguments: ["@assets.packages", "%uploads_directory_name%"]
       tags:
           - { name: twig.extension }